// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/ddns-updater/internal/health (interfaces: AllSelecter,LookupIPer)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=health . AllSelecter,LookupIPer
//

// Package health is a generated GoMock package.
package health

import (
	context "context"
	net "net"
	reflect "reflect"

	records "github.com/qdm12/ddns-updater/internal/records"
	gomock "go.uber.org/mock/gomock"
)

// MockAllSelecter is a mock of AllSelecter interface.
type MockAllSelecter struct {
	ctrl     *gomock.Controller
	recorder *MockAllSelecterMockRecorder
	isgomock struct{}
}

// MockAllSelecterMockRecorder is the mock recorder for MockAllSelecter.
type MockAllSelecterMockRecorder struct {
	mock *MockAllSelecter
}

// NewMockAllSelecter creates a new mock instance.
func NewMockAllSelecter(ctrl *gomock.Controller) *MockAllSelecter {
	mock := &MockAllSelecter{ctrl: ctrl}
	mock.recorder = &MockAllSelecterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllSelecter) EXPECT() *MockAllSelecterMockRecorder {
	return m.recorder
}

// SelectAll mocks base method.
func (m *MockAllSelecter) SelectAll() []records.Record {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAll")
	ret0, _ := ret[0].([]records.Record)
	return ret0
}

// SelectAll indicates an expected call of SelectAll.
func (mr *MockAllSelecterMockRecorder) SelectAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAll", reflect.TypeOf((*MockAllSelecter)(nil).SelectAll))
}

// MockLookupIPer is a mock of LookupIPer interface.
type MockLookupIPer struct {
	ctrl     *gomock.Controller
	recorder *MockLookupIPerMockRecorder
	isgomock struct{}
}

// MockLookupIPerMockRecorder is the mock recorder for MockLookupIPer.
type MockLookupIPerMockRecorder struct {
	mock *MockLookupIPer
}

// NewMockLookupIPer creates a new mock instance.
func NewMockLookupIPer(ctrl *gomock.Controller) *MockLookupIPer {
	mock := &MockLookupIPer{ctrl: ctrl}
	mock.recorder = &MockLookupIPerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLookupIPer) EXPECT() *MockLookupIPerMockRecorder {
	return m.recorder
}

// LookupIP mocks base method.
func (m *MockLookupIPer) LookupIP(ctx context.Context, network, host string) ([]net.IP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupIP", ctx, network, host)
	ret0, _ := ret[0].([]net.IP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupIP indicates an expected call of LookupIP.
func (mr *MockLookupIPerMockRecorder) LookupIP(ctx, network, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupIP", reflect.TypeOf((*MockLookupIPer)(nil).LookupIP), ctx, network, host)
}
