// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/ddns-updater/internal/provider (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -destination=mocks_provider_test.go -package=health github.com/qdm12/ddns-updater/internal/provider Provider
//

// Package health is a generated GoMock package.
package health

import (
	context "context"
	http "net/http"
	netip "net/netip"
	reflect "reflect"

	models "github.com/qdm12/ddns-updater/internal/models"
	ipversion "github.com/qdm12/ddns-updater/pkg/publicip/ipversion"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// BuildDomainName mocks base method.
func (m *MockProvider) BuildDomainName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildDomainName")
	ret0, _ := ret[0].(string)
	return ret0
}

// BuildDomainName indicates an expected call of BuildDomainName.
func (mr *MockProviderMockRecorder) BuildDomainName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildDomainName", reflect.TypeOf((*MockProvider)(nil).BuildDomainName))
}

// Domain mocks base method.
func (m *MockProvider) Domain() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Domain")
	ret0, _ := ret[0].(string)
	return ret0
}

// Domain indicates an expected call of Domain.
func (mr *MockProviderMockRecorder) Domain() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Domain", reflect.TypeOf((*MockProvider)(nil).Domain))
}

// HTML mocks base method.
func (m *MockProvider) HTML() models.HTMLRow {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTML")
	ret0, _ := ret[0].(models.HTMLRow)
	return ret0
}

// HTML indicates an expected call of HTML.
func (mr *MockProviderMockRecorder) HTML() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTML", reflect.TypeOf((*MockProvider)(nil).HTML))
}

// IPVersion mocks base method.
func (m *MockProvider) IPVersion() ipversion.IPVersion {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IPVersion")
	ret0, _ := ret[0].(ipversion.IPVersion)
	return ret0
}

// IPVersion indicates an expected call of IPVersion.
func (mr *MockProviderMockRecorder) IPVersion() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IPVersion", reflect.TypeOf((*MockProvider)(nil).IPVersion))
}

// IPv6Suffix mocks base method.
func (m *MockProvider) IPv6Suffix() netip.Prefix {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IPv6Suffix")
	ret0, _ := ret[0].(netip.Prefix)
	return ret0
}

// IPv6Suffix indicates an expected call of IPv6Suffix.
func (mr *MockProviderMockRecorder) IPv6Suffix() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IPv6Suffix", reflect.TypeOf((*MockProvider)(nil).IPv6Suffix))
}

// Owner mocks base method.
func (m *MockProvider) Owner() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Owner")
	ret0, _ := ret[0].(string)
	return ret0
}

// Owner indicates an expected call of Owner.
func (mr *MockProviderMockRecorder) Owner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Owner", reflect.TypeOf((*MockProvider)(nil).Owner))
}

// Proxied mocks base method.
func (m *MockProvider) Proxied() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Proxied")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Proxied indicates an expected call of Proxied.
func (mr *MockProviderMockRecorder) Proxied() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Proxied", reflect.TypeOf((*MockProvider)(nil).Proxied))
}

// String mocks base method.
func (m *MockProvider) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockProviderMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockProvider)(nil).String))
}

// Update mocks base method.
func (m *MockProvider) Update(ctx context.Context, client *http.Client, ip netip.Addr) (netip.Addr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, client, ip)
	ret0, _ := ret[0].(netip.Addr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProviderMockRecorder) Update(ctx, client, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProvider)(nil).Update), ctx, client, ip)
}
